// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4MKMdrVNBfvR21tUXyeXE1pvK6LjnE3E',
    authDomain: 'the-bawmnet.firebaseapp.com',
    databaseURL: 'https://the-bawmnet-default-rtdb.firebaseio.com',
    projectId: 'the-bawmnet',
    storageBucket: 'the-bawmnet.appspot.com',
    messagingSenderId: '959825450038',
    appId: '1:959825450038:web:85e6b44d76955af3b6b497',
    measurementId: 'G-M4FXZE461H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVyhait1sSt-JnS-2i3Xd7K_mDI8thWT8',
    appId: '1:959825450038:android:7b136620bc4eccddb6b497',
    messagingSenderId: '959825450038',
    projectId: 'the-bawmnet',
    databaseURL: 'https://the-bawmnet-default-rtdb.firebaseio.com',
    storageBucket: 'the-bawmnet.appspot.com',
  );
}
